### ISSUE TITLE
Error while downloading Tidal track

### ISSUE THREAD

**Issue by d3mystified** [TrevTV/Lidarr.Plugin.Tidal#4]
To repro, add Elvis Presley, and mark a couple of albums/singles as monitored. Then hit "Search Monitored".

The same error is repeated to multiple tracks.

```
lidarr  | [Error] TidalProxy: Error while downloading Tidal track 144958625
lidarr  | [Error] TidalProxy: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
lidarr  |    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
lidarr  |    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
lidarr  |    at TidalSharp.API.Call(HttpMethod method, String path, Dictionary`2 formParameters, Dictionary`2 urlParameters, Dictionary`2 headers, String baseUrl, CancellationToken token)
lidarr  |    at TidalSharp.Downloader.GetTrackStreamData(String trackId, AudioQuality quality, CancellationToken token)
lidarr  |    at TidalSharp.Downloader.GetExtensionForTrack(String trackId, AudioQuality quality, CancellationToken token)
lidarr  |    at NzbDrone.Core.Download.Clients.Tidal.Queue.DownloadItem.DoTrackDownload(String track, TidalSettings settings, CancellationToken cancellation)
lidarr  |    at NzbDrone.Core.Download.Clients.Tidal.Queue.DownloadItem.<>c__DisplayClass51_1.<<DoDownload>b__0>d.MoveNext()
```

**Comment by TrevTV** [comment]
I was able to fix the second issue, though the first one is being a lot more of a pain. I can't quite figure out what's causing it.

**Comment by TrevTV** [comment]
Fixed them both, will release soon.
