### ISSUE TITLE
Probing codecs failed

### ISSUE THREAD

**Issue by d3mystified** [TrevTV/Lidarr.Plugin.Tidal#5]
Search for the single and download the Lossless file.

```
[Info] DownloadService: Report sent to Tidal from indexer Tidal. Noah Reid - Simply the Best (From "Schitt's Creek") (2018) [FLAC (M4A) Lossless] [WEB]
[Error] TidalProxy: Error while downloading Tidal track 85298506
[Error] TidalProxy: NzbDrone.Core.Plugins.FFMPEGException: Probing codecs failed
   at NzbDrone.Core.Plugins.FFMPEG.ProbeCodecs(String filePath)
   at NzbDrone.Core.Download.Clients.Tidal.Queue.DownloadItem.HandleAudioConversion(String filePath, TidalSettings settings)
   at NzbDrone.Core.Download.Clients.Tidal.Queue.DownloadItem.DoTrackDownload(String track, TidalSettings settings, CancellationToken cancellation)
   at NzbDrone.Core.Download.Clients.Tidal.Queue.DownloadItem.<>c__DisplayClass51_1.<<DoDownload>b__0>d.MoveNext()
```

Running the latest release.

**Comment by TrevTV** [comment]
Gotcha, the container must have somehow failed to install or just didn't try to install FFMPEG.
