### ISSUE TITLE
Probing codecs failed

### ISSUE THREAD

**Issue by d3mystified** [TrevTV/Lidarr.Plugin.Tidal#9]
Happens frequently. The only workaround is to restart lidarr:

```
2024-12-28 15:00:21.9|Error|TidalProxy|Error while downloading Tidal track 85298506
2024-12-28 15:00:21.9|Error|TidalProxy|NzbDrone.Core.Plugins.FFMPEGException: Probing codecs failed

   at NzbDrone.Core.Plugins.FFMPEG.ProbeCodecs(String filePath)
   at NzbDrone.Core.Download.Clients.Tidal.Queue.DownloadItem.HandleAudioConversion(String filePath, TidalSettings settings)
   at NzbDrone.Core.Download.Clients.Tidal.Queue.DownloadItem.DoTrackDownload(String track, TidalSettings settings, CancellationToken cancellation)
   at NzbDrone.Core.Download.Clients.Tidal.Queue.DownloadItem.<>c__DisplayClass50_1.<<DoDownload>b__0>d.MoveNext()
```

**Comment by TrevTV** [comment]
There's basically nothing to go off of, I can't replicate this issue personally and where there _should_ be some sort of application output log in that error, there's nothing.

**Comment by gssariev** [comment]
Perhaps I can help shed some light on this as I encountered a very similar error:

`[Error] TidalProxy: Error while downloading Tidal track 51970874
lidarr  | [Error] TidalProxy: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'ffprobe' with working directory '/app/bin'. No such file or directory
lidarr  |    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
lidarr  |    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
lidarr  |    at System.Diagnostics.Process.Start()`

Which turned out to be an issue with ffmpeg not being added to the Lidarr container upon building it, even though I followed the steps in the repository. The way I solved is by:

1. `docker exec -it <container-name> /bin/sh`
2. Manually installed ffmpeg using `apk update` and `apk add --no-cache ffmpeg`
3. Created a symbolic link so that Lidarr can see ffprobe: `ln -s $(find /usr/bin -name ffprobe) /app/bin/ffprobe`

After rebooting the container, everything seems to be working as expected - albums get downloaded and imported automatically whereas before the error would be thrown and nothing will happen.

**Comment by TrevTV** [comment]
Odd, not too sure why it wouldn't be getting added. It's possible that I just didn't do it the "proper" way as I'm not super experienced with Docker. Though, I haven't had the issue on my setup so I can't say for sure.

**Comment by TrevTV** [comment]
Are you able to check your downloads folder? It may still have the original `*.m4a` files, if they do exist, upload one here so I can check if you're just downloading data that FFProbe is failing to read.

**Comment by TrevTV** [comment]
I am still unable to replicate it.
```
[Info] DownloadService: Report sent to Tidal from indexer Tidal. Noah Reid - Simply the Best (From "Schitt's Creek") (2018) [FLAC (M4A) Lossless] [WEB]
[Info] ImportDecisionMaker: Reading file 1/1
[Info] TrackGroupingService: Grouping 1 tracks
[Info] IdentificationService: Identifying album 1/1
[Info] ImportApprovedTracks: Importing album 1/1
[Info] ImportApprovedTracks: Importing 1 tracks
```

```
[Info] DownloadService: Report sent to Tidal from indexer Tidal. Meek Mill - Amen (feat. Drake) (2012) [Explicit] [FLAC (M4A) 24bit Lossless] [WEB]
[Info] ImportDecisionMaker: Reading file 1/1
[Info] TrackGroupingService: Grouping 1 tracks
[Info] IdentificationService: Identifying album 1/1
[Info] ImportApprovedTracks: Importing album 1/1
[Info] ImportApprovedTracks: Importing 1 tracks
```

**Comment by TrevTV** [comment]
That file size is way too small, it seems like your host is having issues talking to Tidal? Not sure why it wouldn't end up throwing a different error if that was the case, however.

**Comment by TrevTV** [comment]
Actually I didn't look close enough at the file, some part of your setup isn't working right so it's just failing to get authorization from Tidal, no clue why that would happen.
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access denied</Message>
</Error>
```

**Comment by TrevTV** [comment]
Can you upload the new m4a?

**Comment by TrevTV** [comment]
That m4a is certainly valid, I also downloaded the exact version of ffprobe you're running and it worked so it's not a version issue there. Are you able to install this build of the plugin? I'm hoping it's able to provide actual information in the error log.
[Lidarr.Plugin.Tidal.dll.zip](https://github.com/user-attachments/files/18326384/Lidarr.Plugin.Tidal.dll.zip)

**Comment by TrevTV** [comment]
That would make sense as I've only tested on my testing instance, which is running on Windows

**Comment by TrevTV** [comment]
Awesome, will get that out properly soon.

**Comment by cherryontopknife** [comment]
I experience this issue and need to run the commands [in this comment](https://github.com/TrevTV/Lidarr.Plugin.Tidal/issues/9#issuecomment-2571676346) every time lidarr starts for the error to go away.

**Comment by Karma177** [comment]
```
lidarr | [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f5e2f0f0500] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
lidarr | [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f5e2f0f0500] moov atom not found
lidarr | /lidarr_downloads/tidal/downloads/The Velvet Underground/The Velvet Underground & Nico 45th Anniversary (Deluxe Edition)/02 - 09 - Run Run Run (Alternative Mix).m4a: Invalid data found when processing input
lidarr | at NzbDrone.Core.Plugins.FFMPEG.ProbeCodecs(String filePath)
lidarr | at NzbDrone.Core.Download.Clients.Tidal.Queue.DownloadItem.HandleAudioConversion(String filePath, TidalSettings settings)
lidarr | at NzbDrone.Core.Download.Clients.Tidal.Queue.DownloadItem.DoTrackDownload(String track, TidalSettings settings, CancellationToken cancellation)
lidarr | at NzbDrone.Core.Download.Clients.Tidal.Queue.DownloadItem.<>c__DisplayClass50_1.<b__0>d.MoveNext()
lidarr | [Error] TidalProxy: Error while downloading Tidal track 17639916
lidarr | [Error] TidalProxy: NzbDrone.Core.Plugins.FFMPEGException: Probing codecs failed
lidarr | -select_streams a -show_entries stream=codec_name:stream_tags=language -of default=nk=1:nw=1 "/lidarr_downloads/tidal/downloads/The Velvet Underground/The Velvet Underground & Nico 45th Anniversary (Deluxe Edition)/02 - 11 - Crackin' Up _ Venus In Furs (The Factory Rehearsal).m4a"
lidarr | ffprobe version 8.0.1 Copyright (c) 2007-2025 the FFmpeg developers
lidarr | built with gcc 15.2.0 (Alpine 15.2.0)
lidarr | configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librist --enable-libshaderc --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto=auto --enable-lv2 --enable-openssl --enable-pic --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-vulkan --optflags=-O3 --enable-libsvtav1 --enable-libvpl 
```

For anyone still getting this error, check you have ffmpeg-libavformat installed. That fixed it for me.
